# Generated by Django 5.0.1 on 2024-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_country', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=200)),
                ('temperature', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.URLField()),
                ('city_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
