# Generated by Django 5.0.1 on 2024-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='icon',
            field=models.CharField(max_length=20),
        ),
    ]
