# Generated by Django 5.0.1 on 2024-01-22 16:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('due_date', models.DateField(verbose_name='Due date')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('C', 'Complete'), ('N', 'Not started')], max_length=1, verbose_name='Status')),
                ('main_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='overseer.task')),
            ],
        ),
    ]
