# Generated by Django 5.0.1 on 2024-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('renew_time', models.IntegerField(default=7, verbose_name='Renewal time')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
    ]
