# Generated by Django 5.0.1 on 2024-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0002_renewabletask_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewableTask',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Due date'),
        ),
    ]
