# Generated by Django 5.0.1 on 2024-01-25 21:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0003_delete_renewabletask_alter_subtask_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
