# Generated by Django 5.0.1 on 2024-01-19 11:41

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(help_text='Birthday person', max_length=100, unique=True)),
                ('bdate', models.DateField(help_text='YYYY-MM-DD', verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthdayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('birthday', models.ForeignKey(help_text='Associated birthday', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='memory_crystal.birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('A', 'Archived')], default=0, max_length=1, verbose_name='Status')),
                ('category', models.ManyToManyField(blank=True, help_text='Memo categories', null=True, related_name='memos', to='memory_crystal.category')),
            ],
            options={
                'ordering': ['last_modified', 'pub_date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='memo',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='memory_crystal.memo'),
        ),
    ]
