# Generated by Django 5.0.1 on 2024-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_crystal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='memo',
            field=models.ManyToManyField(blank=True, related_name='categories', to='memory_crystal.memo'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Memo categories', related_name='memos', to='memory_crystal.category'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
