# Generated by Django 5.0.1 on 2024-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_crystal', '0002_alter_category_memo_alter_memo_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='memo',
            name='status',
        ),
        migrations.AlterField(
            model_name='birthday',
            name='person',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
