# Generated by Django 5.0.1 on 2024-01-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_steamgamefeed_websitefeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesForWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_country', models.CharField(max_length=100, verbose_name='City')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedentry',
            options={'ordering': ['-pub_date']},
        ),
    ]
