# Generated by Django 5.0.1 on 2024-01-25 19:25

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_citiesforweather_alter_feedentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesforweather',
            name='city_country',
            field=models.CharField(max_length=100, validators=[dashboard.models.validate_city_country], verbose_name='City'),
        ),
    ]
